// apps/web/components/fountains/FountainPopup.tsx
"use client";

import { DogIcon, WrenchIcon } from "@phosphor-icons/react";
import type { Fountain } from "@rosm/core/schemas";
import { fountainName, isDogWater, isOutOfService } from "@rosm/core/fountainFilters";
import { fmtDist } from "@rosm/core/geo";

// Read-only popup: name, last-checked date, status flags, OSM link. No edit
// controls — this view is purely for finding water nearby.
export default function FountainPopup({ f, distM }: { f: Fountain; distM: number | null }) {
  return (
    <div className="flex w-52 flex-col gap-1 text-neutral-800">
      {f.tags.name && <div className="leading-tight font-semibold">{fountainName(f)}</div>}
      {distM != null && <div className="text-xs text-neutral-500">{fmtDist(distM)} away</div>}
      {f.tags.check_date ? (
        <div className="text-xs text-neutral-500">Last checked in OSM: {f.tags.check_date}</div>
      ) : (
        <div className="text-xs text-neutral-500">Never verified on the ground</div>
      )}
      {isDogWater(f.tags) && (
        <div className="mt-1 flex items-center gap-1 text-xs font-medium text-violet-700">
          <DogIcon size={14} /> Dog water — not for humans
        </div>
      )}
      {isOutOfService(f.tags) && (
        <div className="mt-1 flex items-center gap-1 text-xs font-medium text-amber-700">
          <WrenchIcon size={14} /> Marked out of service
        </div>
      )}
      <a
        href={`https://www.openstreetmap.org/node/${f.id}`}
        target="_blank"
        rel="noreferrer"
        className="mt-1 text-xs font-medium text-blue-600 underline underline-offset-2"
      >
        View on OpenStreetMap
      </a>
    </div>
  );
}

// apps/site/src/components/fountains/FountainPopup.svelte
<script lang="ts">
  import { NavigationArrowIcon, WrenchIcon } from "phosphor-svelte";
  import DogIcon from "@/components/icons/DogIcon.svelte";
  import type { Fountain } from "@rosm/core/schemas";
  import { fountainName, isDogWater, isOutOfService } from "@rosm/core/fountainFilters";
  import { checkedAgoLabel } from "@rosm/core/checkDate";
  import { bearing, compass, fmtDist, haversine, type Pt } from "@rosm/core/geo";

  // Read-only popup: name, how far (once we know where the visitor is), last-
  // checked date, status flags. No edit controls — this view is purely for
  // finding water nearby.
  let {
    f,
    userPos = null,
    onDirections,
  }: {
    f: Fountain;
    // The visitor's fix, if they've shared one. With it the popup shows the
    // straight-line distance and which way to look; the walking route itself
    // lives in the panel under the map, which the parent opens on selection.
    userPos?: Pt | null;
    // Without a fix there is no route yet — this asks for one. Only rendered
    // in that state: once located, selecting a fountain already routes to it.
    onDirections?: () => void;
  } = $props();

  // Snapshot the clock once — the "checked ago" label doesn't need to tick live.
  const now = Date.now();

  const distance = $derived(
    userPos ? `${fmtDist(haversine(userPos, f))} ${compass(bearing(userPos, f))}` : null,
  );
</script>

<div class="flex w-52 flex-col gap-1 text-neutral-800">
  <div class="flex items-start justify-between gap-2">
    <div class="min-w-0">
      <div class="leading-tight font-semibold">{fountainName(f)}</div>
      <div class="mt-0.5 text-xs text-neutral-600">
        {#if distance}
          {distance} · {checkedAgoLabel(f.tags, now)}
        {:else}
          {checkedAgoLabel(f.tags, now)}
        {/if}
      </div>
    </div>
    {#if !userPos && onDirections}
      <button
        type="button"
        aria-label="Directions"
        title="Directions"
        onclick={onDirections}
        class="flex size-8 shrink-0 items-center justify-center rounded-lg text-neutral-800 transition hover:bg-neutral-900/5 active:scale-95"
      >
        <NavigationArrowIcon size={18} weight="fill" />
      </button>
    {/if}
  </div>
  {#if isDogWater(f.tags)}
    <div class="mt-1 flex items-center gap-1 text-xs font-medium text-violet-700">
      <DogIcon size={14} /> Dog water — not for humans
    </div>
  {/if}
  {#if isOutOfService(f.tags)}
    <div class="mt-1 flex items-center gap-1 text-xs font-medium text-amber-700">
      <WrenchIcon size={14} /> Out of order
    </div>
  {/if}
</div>
